# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

begin
	if Race.all.count == 0
		Race.create([
	    	{name: "Perro Mestizo"},
	    {name: "Affenpinscher"},
	    {name: "Afgano"},
	    {name: "Aïdi"},
	    {name: "Akbash"},
	    {name: "Akita Americano (Gran Perro Japonés)"},
	    {name: "Akita Inu"},
	    {name: "Alano Español"},
	    {name: "Alapaha (Bulldog de Sangre Azul)"},
	    {name: "Azawahk"},
	    {name: "Barbet"},
	    {name: "Basenji"},
	    {name: "Basset Hound"},
	    {name: "Beagle"},
	    {name: "Beauceron (Pastor de Beauce)"},
	    {name: "Bedlington Terrier"},
	    {name: "Bichón Boloñés"},
	    {name: "Bichón Frisé"},
	    {name: "Bichón Habanero"},
	    {name: "Bloodhound"},
	    {name: "Blue Lacy"},
	    {name: "Boerboel"},
	    {name: "Border Collie"},
	    {name: "Border Terrier"},
	    {name: "Borzoi Collie"},
	    {name: "Boston Terrier"},
	    {name: "Boxer"},
	    {name: "Boyero de Appenzell"},
	    {name: "Boyero de Berna"},
	    {name: "Boyero de Entlebuch"},
	    {name: "Boyero de Flandes"},
	    {name: "Boyero de Las Ardenas"},
	    {name: "Boykin Spaniel"},
	    {name: "Braco Alemán"},
	    {name: "Braco de Auvernia"},
	    {name: "Braco de Bourbonnais"},
	    {name: "Braco de Sant Germain"},
	    {name: "Braco de Weimar (Weimaraner)"},
	    {name: "Braco Francés Tipo Gascuña"},
	    {name: "Braco Wire Alemán"},
	    {name: "Bretón Spaniel"},
	    {name: "Briquet Grifón"},
	    {name: "Buhund Noruego"},
	    {name: "Bull Terrier"},
	    {name: "Bulldog"},
	    {name: "Bulldog Americano"},
	    {name: "Bulldog Francés"},
	    {name: "Bullmastiff"},
	    {name: "Ca de Bestiar (Pastor Mallorquín)"},
	    {name: "Ca De Bou"},
	    {name: "Cairn Terrier"},
	    {name: "Cane Corso"},
	    {name: "Cao Da Serra Da Estrela"},
	    {name: "Carolina Dog"},
	    {name: "Catahoula Leopard"},
	    {name: "Charplaninatz"},
	    {name: "Chesapeake Bay Retriever"},
	    {name: "Chi-Poo"},
	    {name: "Chien Français"},
	    {name: "Chihuahua"},
	    {name: "Chino Crestado Enano"},
	    {name: "Chow Chow"},
	    {name: "Cimarrón"},
	    {name: "Cirneco de Etna"},
	    {name: "Clumber Spaniel"},
	    {name: "Cocker Inglés"},
	    {name: "Cocker Spaniel Americano"},
	    {name: "Collie"},
	    {name: "Collie Smooth"},
	    {name: "Coonhound"},
	    {name: "Corgi Galés Cardigan"},
	    {name: "Coton de Tulear"},
	    {name: "Dachshund (Salchicha oTeckel)"},
	    {name: "Dálmata"},
	    {name: "Dandie Dinmont Terrier"},
	    {name: "Deutscher Jagdterrier"},
	    {name: "Dobermann"},
	    {name: "Dogo Argentino"},
	    {name: "Dogo de Burdeos"},
	    {name: "Dogo del Tibet"},
	    {name: "Epañeul Enano"},
	    {name: "Epañeul Francés"},
	    {name: "Epañeul Tibetano"},
	    {name: "Fila Brasileño"},
	    {name: "Fox Terrier"},
	    {name: "Fox Terrier Wire (Fox Terrier Pelo Alambre)"},
	    {name: "Foxhound"},
	    {name: "Galgo Español"},
	    {name: "Galgo Italiano"},
	    {name: "Golden Retriever"},
	    {name: "Gran Danés"},
	    {name: "Greyhound"},
	    {name: "Griffón Nivernais"},
	    {name: "Grifón Azul de Gascuña"},
	    {name: "Grifón de Bruselas"},
	    {name: "Groenlandés (Grünlandshund)"},
	    {name: "Harrier"},
	    {name: "Hellenikos Ichnilatis (Sabueso Griego)"},
	    {name: "Hovawart"},
	    {name: "Jack Russell Terrier"},
	    {name: "Karelian Bear Dog"},
	    {name: "Keeshond"},
	    {name: "Kelpie Australiano"},
	    {name: "King Charles Spaniel"},
	    {name: "Kleiner Münsterländer"},
	    {name: "Komondor"},
	    {name: "Koolie"},
	    {name: "Korthals"},
	    {name: "Kromforlander"},
	    {name: "Kuvasz"},
	    {name: "Kyushu (Perro de Hokkaido)"},
	    {name: "Labradoodle"},
	    {name: "Labrador"},
	    {name: "Lagotto Romagnolo"},
	    {name: "Laika Ruso Europeo"},
	    {name: "Lapphund"},
	    {name: "Lebrel Escocés"},
	    {name: "Lebrel Irlandés"},
	    {name: "Leonberger"},
	    {name: "Lhassa Apso"},
	    {name: "Lowchen (Pequeño Perro León)"},
	    {name: "Lurcher"},
	    {name: "Malamute de Akaska (Alaskan Malamute)"},
	    {name: "Maltés"},
	    {name: "Manchester Terrier"},
	    {name: "Maremma Sheepdog"},
	    {name: "Mastín de los Pirineos"},
	    {name: "Mastín Español"},
	    {name: "Mastín Inglés"},
	    {name: "Mastín Napolitano"},
	    {name: "Montaña de los Pirineos"},
	    {name: "Mudi"},
	    {name: "Otterhound (Perro de Nutria)"},
	    {name: "Ovejero Inglés"},
	    {name: "Ovejero Rumano (Carpathian Sheepdog)"},
	    {name: "Ovejero Shetland"},
	    {name: "Papillon"},
	    {name: "Pastor Alemán"},
	    {name: "Pastor Australiano"},
	    {name: "Pastor Belga"},
	    {name: "Pastor Belga Laekenois"},
	    {name: "Pastor Belga Malinois"},
	    {name: "Pastor Belga Tervuren"},
	    {name: "Pastor Bergamasco"},
	    {name: "Pastor Blanco Suizo"},
	    {name: "Pastor Catalán"},
	    {name: "Pastor Croata"},
	    {name: "Pastor de Anatolia"},
	    {name: "Pastor de Brie"},
	    {name: "Pastor de Shiloh"},
	    {name: "Pastor del Cáucaso"},
	    {name: "Pastor Holandés"},
	    {name: "Pastor Inglés (Ovejero Inglés, Bobtail)"},
	    {name: "Pastor Polaco"},
	    {name: "Pastor Vasco (Euskal Artzain Txakurra)"},
	    {name: "Pekinés"},
	    {name: "Pequeño Brabantino"},
	    {name: "Perdiguero de Burgos"},
	    {name: "Perro de Aguas Español"},
	    {name: "Perro de Aguas Portugués"},
	    {name: "Perro de Canaan"},
	    {name: "Perro sin Pelo del Perú"},
	    {name: "Pharaoh Hound (Perro de los Faraones)"},
	    {name: "Pinscher Miniatura"},
	    {name: "Pit Bull Terrier"},
	    {name: "Podenco Canario"},
	    {name: "Podenco Ibicenco"},
	    {name: "Podenco Portugués"},
	    {name: "Pointer"},
	    {name: "Pomerania"},
	    {name: "Poodle (Caniche)"},
	    {name: "Porcelana"},
	    {name: "Presa Canario"},
	    {name: "Pug (Carlino)"},
	    {name: "Puli"},
	    {name: "Pumi"},
	    {name: "Rafeiro Do Alentejo"},
	    {name: "Rhodesian Ridgebak"},
	    {name: "Rottweiler"},
	    {name: "Rough Collie"},
	    {name: "Sabueso de Istria"},
	    {name: "Sabueso del Jura (Jura Laufhund)"},
	    {name: "Sabueso Español"},
	    {name: "Sabueso Italiano"},
	    {name: "Sabueso Lituano"},
	    {name: "Saluki (Lebrel Persa)"},
	    {name: "Samoyedo"},
	    {name: "San Bernardo"},
	    {name: "Schapendoes"},
	    {name: "Schipperke"},
	    {name: "Schnauzer Estándar"},
	    {name: "Schnauzer Gigante"},
	    {name: "Schnauzer Miniatura"},
	    {name: "Scottish Terrier"},
	    {name: "Setter Gordon"},
	    {name: "Setter Inglés"},
	    {name: "Setter Irlandés"},
	    {name: "Shar Pei"},
	    {name: "Shiba Inu"},
	    {name: "Shih-Tzu"},
	    {name: "Siberiano (Husky Siberiano)"},
	    {name: "Sloughi"},
	    {name: "Spaniel Azul de Picardía"},
	    {name: "Spaniel Japonés"},
	    {name: "Spinone Italiano"},
	    {name: "Spitz Enano"},
	    {name: "Spitz Finlandés"},
	    {name: "Spitz Japonés"},
	    {name: "Stafford Terrier Americano"},
	    {name: "Staffordshire Bull Terrier"},
	    {name: "Sussex Spaniel"},
	    {name: "Terranova"},
	    {name: "Terrier Airedale"},
	    {name: "Terrier Australiano (Terrier Silky)"},
	    {name: "Terrier Cesky"},
	    {name: "Terrier Galés"},
	    {name: "Terrier Kerry Blue"},
	    {name: "Terrier Lakeland"},
	    {name: "Terrier Norfolk"},
	    {name: "Terrier Norwich"},
	    {name: "Terrier Sealyham"},
	    {name: "Terrier Skye"},
	    {name: "Terrier Tibetano"},
	    {name: "Toller (Nova Scotia Duck)"},
	    {name: "Tosa Inu"},
	    {name: "Toy Fox Terrier (American Toy Terrier, Amertor)"},
	    {name: "Västgötaspets (Perro de los Visigodos)"},
	    {name: "Viszla"},
	    {name: "West Highland White Terrier"},
	    {name: "Wetterhoun"},
	    {name: "Whippet"},
	    {name: "Wolfdog Checoeslovaco"},
	    {name: "Wolfhound Irlandés"},
	    {name: "Xoloitzcuintle"},
	    {name: "Yorkshire Terrier"}
	    ])
		puts 'Razas agregadas con éxito'
	else
		puts 'Las razas ya han sido agregadas'
	end
rescue Exception => e
	
end

begin
	Client.create([
								{id: 1, clientRut: "1-9",clientName: "Cliente", clientLastName: "1", clientEmail: "cliente@mail.com", clientCellPhone: "99999", clientAddress: "calle bonita 123"}
								])
	puts 'Cliente agregado con éxito'
rescue Exception => e
	puts 'WARNING: Clientes ya agregados'
end

begin
	Role.create([
						{id: 1, name: 'Admin'},
						{id: 2, name: 'Recepcionista'},
						])
	puts 'Roles creados con éxito'
rescue Exception => e
	puts 'WARNING: Los roles ya están agregados'
end